"""allow_anonymous_interactions

Revision ID: bc9e689a6020
Revises: 
Create Date: 2026-01-23 13:52:03.523263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'bc9e689a6020'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle_interactions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('puzzle_templates', schema=None) as batch_op:
        batch_op.alter_column('difficulty_score',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('difficulty_data',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))

    with op.batch_alter_table('puzzles', schema=None) as batch_op:
        batch_op.alter_column('short_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('template_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_puzzles_short_id'), ['short_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_puzzles_template_id'), ['template_id'], unique=False)
        batch_op.create_foreign_key(None, 'puzzle_templates', ['template_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('puzzles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_puzzles_template_id'))
        batch_op.drop_index(batch_op.f('ix_puzzles_short_id'))
        batch_op.alter_column('template_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('short_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('puzzle_templates', schema=None) as batch_op:
        batch_op.alter_column('difficulty_data',
               existing_type=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('difficulty_score',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('puzzle_interactions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
